//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class bid
    {
        public int bid_id { get; set; }
        public int property_id { get; set; }
        public int buyer_id { get; set; }
        public Nullable<long> status { get; set; }
    
        public virtual bid_price bid_price { get; set; }
        public virtual buyer buyer { get; set; }
        public virtual property property { get; set; }
    }
}
