//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class bid_price
    {
        public int bid_id { get; set; }
        public Nullable<double> plot_price { get; set; }
        public Nullable<double> apartment_price { get; set; }
    
        public virtual bid bid { get; set; }
    }
}
