//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyer
    {
        public buyer()
        {
            this.bids = new HashSet<bid>();
        }
    
        public int buyer_id { get; set; }
        public Nullable<long> min_cost { get; set; }
        public Nullable<long> max_cost { get; set; }
        public Nullable<double> min_area { get; set; }
        public Nullable<double> max_area { get; set; }
        public long user_id { get; set; }
    
        public virtual ICollection<bid> bids { get; set; }
        public virtual user user { get; set; }
    }
}
