//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class landmark
    {
        public landmark()
        {
            this.properties = new HashSet<property>();
        }
    
        public long landmark_id { get; set; }
        public string name { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public int landmarktype { get; set; }
    
        public virtual landmarktype landmarktype1 { get; set; }
        public virtual ICollection<property> properties { get; set; }
    }
}
