//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEntities : DbContext
    {
        public RealEntities()
            : base("name=RealEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bid> bids { get; set; }
        public DbSet<bid_price> bid_price { get; set; }
        public DbSet<buyer> buyers { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<landmark> landmarks { get; set; }
        public DbSet<landmarktype> landmarktypes { get; set; }
        public DbSet<min_price> min_price { get; set; }
        public DbSet<property> properties { get; set; }
        public DbSet<propery_status> propery_status { get; set; }
        public DbSet<seller> sellers { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<image> images { get; set; }
    }
}
